### PR TITLE
Convert df to pyspark DataFrame if it is pandas before writing

### LINKED ISSUE #312: [Feature] Support python model return a pandas dataframe
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When dbt python model returns a pandas dataframe, dbt will handle materialize it as table

### Describe alternatives you've considered

_No response_

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chamini2**
resolves #312

### Description

This adds a check for the `df` returned from the `model` function to convert into pyspark DataFrame if it's pandas.

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by jtcohen6** [comment]
[Original community Slack thread](https://getdbt.slack.com/archives/C03QUA7DWCW/p1662367521265629)

@lostmygithubaccount I believe this change would resolve the bug that @b-per ran into during yesterday's hackathon, by checking to see if the user is returning a Pandas dataframe and converting it back to a PySpark dataframe before writing it back to the database.

We should make the same change over in `dbt-spark` as well. (Another argument for finding a place to store PySpark-specific code, so it doesn't need to be copy-pasted between these two.)

**Comment by chamini2** [comment]
Should I open a ticket @jtcohen6 ?

**Comment by lostmygithubaccount** [comment]
@chamini2 nothing on your end, appreciate the contribution! we're doing some manual testing before final review/merge

**Comment by dbeatty10** [comment]
I manually verified that the following didn't work before. Confirmed that it works using @chamini2's fix 👍 

```python
import pandas as pd

def model(dbt, session):
    dbt.config(
        materialized="table",
        packages=["pandas"]
    )

    df = pd.DataFrame(
        {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
        'Country': ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Venezuela'],
        'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
        'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]}
        )

    return df
```

**Review by ChenyuLInx — APPROVED** [review]

**Comment by ChenyuLInx** [comment]
@chamini2  Thanks for contributing this!!!

@dbeatty10 thanks for confirming it! I will add this as a basic tests in core!

**Pull request merged**
