### PR TITLE
fix in dev_requirements reference in contributing.md

### PR DESCRIPTION
**Pull request by McKnight-42**
### Description

changes dev-requirements.txt -> dev_requirements.txt

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-bigquery next" section.

### CODE REVIEW

**Comment by kwigley** [comment]
do you think it makes sense to align with dbt-core's naming and change the file name and all references to it? It is named dev-requirements.txt over there https://github.com/dbt-labs/dbt-core/blob/main/dev-requirements.txt

**Comment by McKnight-42** [comment]
I think the all the adapters if i'm not mistaken are on dev_requirements so either way swapping ref in contributing.md or changing the file name seems about same amount of pr's technically but if going to be fully aligned namespace wise is a gain yeah that might be better choice.

**Review by kwigley — CHANGES_REQUESTED** [review]
request to rename file instead of updating docs here

**Comment by leahwicz** [comment]
@McKnight-42 can we close this out then since we went with renaming?

**Pull request closed without merging**
