### PR TITLE
Support BigQuery 'labels' and 'hours_to_expiration' configs for seeds

### LINKED ISSUE #125: [CT-264] [CT-262] [Feature] Support BigQuery labels for seeded models
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Current models support `+labels:` config as follows:
```
models:
  my_project:
    snowplow:
      +labels:
        domain: clickstream
```

However, seeded models do not currently support this, at least not that I am aware. Having the `+labels:` config under `seeds:` do not currently result in labels being set when running `dbt seed` to the database.

### Describe alternatives you've considered

I have written a macro that is always run as a post-hook for all seeded models.

```
{% macro set_labels_to_seed_models(model_ref) -%}
    {% if execute %}
        {{ log("set_labels_to_seed_models: About to add labels to model: " ~ model_ref) }}
        {% set set_label_to_model_query %}
            ALTER TABLE {{ model_ref }}
            SET OPTIONS (
                labels=[("domain", "clickstream")]
            )
        {% endset %}
        {%- set result = run_query(set_label_to_model_query) -%}
    {% endif %}

{%- endmacro %}
```

And in `dbt_project.yml`, I attach the macro as a post-hook to all models in seeds config:
```
seeds:
  my_project:
    snowplow:
        +post-hook: "{{ set_labels_to_seed_models(this) }}"
```

### Who will this benefit?

BigQuery users who need to seed data into the database but also need labels applied.

### Are you interested in contributing this feature?

Yes, if this is a feature that is wanted.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by darrylng**
resolves #125

### Description

This PR enables `+labels:` and `+hours_to_expiration:` configs for seeds configuration. These labels are already implemented and used by models configuration to set table/view labels and expiration time, but was not done for seeded tables, reasons explained in issue #125.

The initial change was to only implement `labels` config but on further dev, I noticed the addition of `ALTER TABLE .. SET OPTION()` [supports other options](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_set_options_statement) other than `labels`, so the pytest was added to include `hours_to_expiration` config test as well.

These are the only two [non-configs properties](https://docs.getdbt.com/reference/configs-and-properties#which-properties-are-not-also-configs) that are currently implemented in `dbt-bigquery` that will start to take effect with the change in `seed.sql`.

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-bigquery next" section.

### CODE REVIEW

**Comment by McKnight-42** [comment]
Hi @darrylng sorry for the wait on review if you could update to current main and push up to clear up current conflicts that would be great as it keeps your local in step with your pushed up pr.

**Comment by McKnight-42** [comment]
@darrylng it seems that we have added the pre-commit since you last updated, if you could update your local and run the pre-commit checks to make sure its passing should clear up the code-quality test. sorry for the delay in response.

**Comment by McKnight-42** [comment]
@darrylng really liking this tested locally and tests are passing, not sure why more aren't triggering here. if you could please update to latest in main and re push up (want to just keep your remote and local up to date with each other). but this is looking very good thus far great work!

**Comment by McKnight-42** [comment]
@darrylng really liking this tested locally and tests are passing, not sure why more aren't triggering here. if you could please update to latest in main and re push up (want to just keep your remote and local up to date with each other). but this is looking very good thus far great work!

**Comment by darrylng** [comment]
I have merged main branch into my forked branch but I believe the three tests that aren't running is because I'm a first time contributor and the workflow requires a maintainer to approve running it. 
Reference:
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by matthieu-lombard** [comment]
Any news on this request ?
It would be appreciated to clean seeds after ci jobs

**Review by McKnight-42 — APPROVED** [review]
@darrylng thank you for working on this sorry its taken longer than anticipated to get it in great work on this!

**Pull request merged**
