### PR TITLE
Adding execution_project to target object

### PR DESCRIPTION
**Pull request by pgoslatara**
resolves #4267

### Description

Adding the optional `execution_project` param from `profile.yml` to the `target` object.

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-bigquery next" section.

### CODE REVIEW

**Comment by pgoslatara** [comment]
Linking #67.

**Comment by jtcohen6** [comment]
Closing and reopening to trigger integration tests

**Review by jtcohen6 — COMMENTED** [review]
Thanks for the contribution @pgoslatara, this is looking good! Could I just ask you to add an entry to the top of `CHANGELOG.md`?

**Comment by pgoslatara** [comment]
> Thanks for the contribution @pgoslatara, this is looking good! Could I just ask you to add an entry to the top of `CHANGELOG.md`?

@jtcohen6 Done, hope I formatted it correctly! 17acb2b

**Review by jtcohen6 — APPROVED** [review]

**Pull request merged**
