### PR TITLE
fixup #225 - fix logged job link

### PR DESCRIPTION
**Pull request by MartinNowak**
fixup #250 

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by MartinNowak** [comment]
Any chance we can get this reviewed and merged before 1.3.0 @McKnight-42 @jtcohen6

**Comment by Fleid** [comment]
Hey @MartinNowak, sorry for the delay.
I can't find a reason that motivates the switch, have I missed a conversation somewhere? Thanks!

**Comment by VersusFacit** [comment]
We'll need some context here to explain why we need to change the order of the `if` statement. Is this meant to be primarily syntactic? Because shifting the parameters could introduce boolean short-circuit related changes in logic.

Also, is the order of these parameters wrong? Certainly share the context that led to these changes ✌️

**Comment by Fleid** [comment]
I'll close for now, please re-open if need be!

**Pull request closed without merging**
