### PR TITLE
Retry query jobs and use info-level logging for job link, etc

### LINKED ISSUE #696: [Feature] Move the BQ Job link after the job submission instead of job done
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

So far the job link is logged once the fails or if the debug mode is enabled and the job is done.
However in a lot of cases, if you want to follow a job execution for a long running one (ie to look at execution plan or access the UI to cancel it manually), you have to find it again by using the job search on the UI/CLI which is inconvenient.

Moving the log earlier in the process (after the job submission but before it's done) will ease the operational side for engineers.

### Describe alternatives you've considered

_No response_

### Who will this benefit?

Anyone monitoring/troubleshooting BigQuery query using debug mode

### Are you interested in contributing this feature?

yes

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tbog357**
resolves #696

### Description

Improve productivity, provide the Bigquery job's link just after it's submitted. Make it easier to find the executed queries

Example of logs proposal
image

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by tbog357** [comment]
I have just signed the CLA, how can I retrigger the workflow?

**Review by github-christophe-oudar — CHANGES_REQUESTED** [review]
Hello,
Thanks for raising the PR!
I've implemented most of it in https://github.com/dbt-labs/dbt-bigquery/pull/630.
Yet you're adding few things in this one that could be making it more worthwhile:
- retries on the query job call with an error counter
- a link that includes the attempts, materialization, incremental resource type & node name
- add it as an info log

I think your approach is great but it might require some changes:
- Do you think we could align the info in [the error log](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/connections.py#L222) too? I think it's fine to log it twice to easily find the job link in case of error.
- the error counter starts at 0 which is kind of weird to me, what about making it start at 1 and stop after 2 retries (so 3 total)? Maybe even make it a configurable thing but I guess it's more work than needed so far.
- Is it catching all errors? For instance, if I have a SQL or runtime BQ error and it fails, will it start and retry it on every dbt run? I think most people would rather avoid that behavior. So I'm bit worried about introducing that retry especially since 1.6 introduces already `dbt retry`.
- If you're adding this log, you should remove https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/connections.py#LL537C4-L537C4 as it would be obsolete then

**Review by dbeatty10 — CHANGES_REQUESTED** [review]
@tbog357 A handful of things for you to do:
1. [Open a feature request](https://github.com/dbt-labs/dbt-bigquery/issues/new?assignees=&labels=enhancement%2Ctriage&projects=&template=feature-request.yml&title=%5BFeature%5D+%3Ctitle%3E) for converting from debug-level to info-level (c.f. [here](https://github.com/dbt-labs/dbt-bigquery/pull/697/files#r1214624049))
1. [Open a feature request](https://github.com/dbt-labs/dbt-bigquery/issues/new?assignees=&labels=enhancement%2Ctriage&projects=&template=feature-request.yml&title=%5BFeature%5D+%3Ctitle%3E) for retrying query jobs
1. Update the changelog entry to reflect those two feature request issue numbers (and removing [696](https://github.com/dbt-labs/dbt-bigquery/pull/696) which was already resolved)
1. Update the changelog entry description [here](https://github.com/dbt-labs/dbt-bigquery/pull/768/files#r1261368468)

Both of those feature requests will need to be approved by our product team (i.e., @fleid or @dataders)

**Comment by tbog357** [comment]
Hi @dbeatty10 , thanks for reminding me

1. I think logging the job-link at the debug-level is reasonable.

2. This PR doesn't try to implement a retry feature, it just shows the count of retries if profiles.yml have job_retries configuration https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#job_retries

But the PR of @github-christophe-oudar (https://github.com/dbt-labs/dbt-bigquery/pull/697) suited my need. So I will close this PR

Thanks all

**Pull request closed without merging**
