### PR TITLE
fix: cast dataproc batch runtime props

### LINKED ISSUE #1001: [ADAP-1007] [Feature] Cast dataproc batch runtime_config properties to strings
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

While trying to configure Dataproc Serverless jobs via `profile.yml`, I keep getting an error unless I use quotes around each key-value pair, which doesn't match [dbt's documentation](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#running-python-models-on-dataproc).

What works for me:

```yml
runtime_config:
          properties:
           'spark.executor.instances': '4'
            'spark.driver.memory': '4g'
```

### Expected Behavior

According to [dbt's documentation](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#running-python-models-on-dataproc), Dataproc Serverless jobs can be configured in the dbt `profiles.yml`  file, without quotes. In the example provided on the site, `runtime_config` `properties` can be specified in yaml as such:

```yml
runtime_config:
          properties:
            spark.executor.instances: 3
            spark.driver.memory: 1
```

### Steps To Reproduce

1.  You have dbt python models already in your project
2.  Add runtime_config properties for serverless jobs without quotes
3.  Run your dbt-py model

### Relevant log output

```shell
Unable to parse dataproc_batch as valid batch specification. See https://cloud.google.com/dataproc-serverless/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.Batch. Failed to parse runtime_config field: Failed to parse properties field: expected string or bytes-like object..
```

### Environment

```markdown
- OS: Mac OS Sonoma 14.1
- Python: 3.9.6
- dbt-core: 1.6.2
- dbt-bigquery: 1.6.4
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jimmyshah**
resolves #1001 

### Problem
There is a bug currently that requires `runtime_config` `properties` values to be strings. As a result, integer values need quotes around them in the yml files, which is awkward.

With this PR, values are cast as strings, so that the properties can be set in a more expected way.

[ADAP-1007]

### Solution
In `_configure_batch()`, I added a check for `runtime_config.properties`. If they exist, I iterate through the dictionary to cast the values as strings. Changing this part of the code was suggested as an option in #1001. 

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

[ADAP-1007]: https://dbtlabs.atlassian.net/browse/ADAP-1007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jimmyshah** [comment]
Hey @dbeatty10 @McKnight-42! Anything I can do to help move this PR forward? 

Unrelated: I signed the CLA and have signed my git commits, but not sure why the cla-bot is disagreeing. Apologies for the mess...

**Comment by dbeatty10** [comment]
@cla-bot check

**Comment by dbeatty10** [comment]
### CLA

> I signed the CLA and have signed my git commits, but not sure why the cla-bot is disagreeing. Apologies for the mess...

I'm guessing that the cla-bot is complaining about [these](https://github.com/dbt-labs/dbt-bigquery/pull/1008/commits) two commits (a1f1608effe59944aec97f6e96859eb545e0108d and 3072f30d71918f02f8c5de43ff3ffff976c0af54):

image

### Easiest path forward

> My formatter/editor settings may have caused more changes than I intended, my apologies. I only meant to add these [lines](https://github.com/dbt-labs/dbt-bigquery/pull/1008/files#diff-2624b5c88e526f5e8f936d4878fdadac2bd2d135950bdd95dc432209f7700352R184-R186)
> 
> If there is anything else I can do from my end, let me know!

The easiest thing at this point might be just to open a new PR. That way, all the commits would have the same identity that signed the CLA.

Also, if your PR adds _only_ these [lines](https://github.com/dbt-labs/dbt-bigquery/pull/1008/files#diff-2624b5c88e526f5e8f936d4878fdadac2bd2d135950bdd95dc432209f7700352R184-R186), then you'll be more likely to pass our code-formatting checks too.

### Alternative path forward

You could also try keeping this PR by:
`. undo all changes except for these [lines](https://github.com/dbt-labs/dbt-bigquery/pull/1008/files#diff-2624b5c88e526f5e8f936d4878fdadac2bd2d135950bdd95dc432209f7700352R184-R186)
1. rebase all your commits and force-pushing

I'm guessing you'll find opening a new PR to be a bit easier, but either way works for us.

**Comment by jimmyshah** [comment]
Thanks for the suggestion @dbeatty10. I just opened a new PR https://github.com/dbt-labs/dbt-bigquery/pull/1024 and the issues seem to be resolved. I'll close the PR.

**Pull request closed without merging**
