### PR TITLE
Ensuring dataset exists prior to loading seed

### LINKED ISSUE #88: dbt seed fails on capital letters in dataset names
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `dbt seed` with a dataset name that includes capital letters it fails eg if using "Bananas" instead of "bananas"

### Expected Behavior

That it would work fine.

### Steps To Reproduce

_No response_

### Relevant log output

```shell
10:45:53 | Concurrency: 1 threads (target='caoilte')
10:45:53 | 
10:45:53 | 1 of 1 START seed file caoilte_Bananas_raw.seed_top1300 [RUN]
Unhandled error while executing seed.fruit.seed_top1300
404 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/banana-project/jobs?uploadType=resumable: Not found: Dataset banana-project:caoilte_Bananas_raw
10:45:53 | 1 of 1 ERROR loading seed file caoilte_Bananas_raw.seed_top1300 [ERROR in 0.27s]
10:45:53 | 
10:45:53 | Finished running 1 seed in 5.72s.

Completed with 1 error and 0 warnings:

404 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/banana-project/jobs?uploadType=resumable: Not found: Dataset banana-project:caoilte_Bananas_raw
```
```


### Environment

```markdown
- OS: Linux
- Python: 3.8.6
- dbt: 0.21.0
```

### What database are you using dbt with?

bigquery

### Additional Context

dbt/bigquery works fine for capitalised model names (It was trying to make the seed name consistent with the capitalised model name that highlighted the bug)

### PR DESCRIPTION
**Pull request by pgoslatara**
resolves #88

### Description

Ensures dataset exists prior to loading data from seed.

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-bigquery next" section.

### CODE REVIEW

**Comment by McKnight-42** [comment]
hi @pgoslatara if you could update to latest main we can check that tests are still passing sorry for belated feedback.

**Comment by pgoslatara** [comment]
> hi @pgoslatara if you could update to latest main we can check that tests are still passing sorry for belated feedback.

@McKnight-42 Done, however the flake8 test timed out, not sure why, maybe you could re-trigger the tests?

**Comment by McKnight-42** [comment]
@pgoslatara  no problem, i've noticed that test hang up a few times lately will look into it as well.

**Comment by McKnight-42** [comment]
@pgoslatara I really appreciate you taking the time to run up this check, after working with the original issue opener and finding that their case was in a different vein, and a senior member of my team pointed me to[create_schema](https://github.com/dbt-labs/dbt-core/blob/a588607ec6546de441812e215fbbf4e9ff20101b/core/dbt/task/runnable.py#L515) and [adapter_create_schema](https://github.com/dbt-labs/dbt-core/blob/a588607ec6546de441812e215fbbf4e9ff20101b/core/dbt/task/runnable.py#L550) which seems to handle the same thing your test would. I'll go ahead and close this PR, and really yet again thank you so much for working back and forth with me.

**Pull request closed without merging**
