### PR TITLE
Fixes adding policy tags when a struct is defined in the yml

### LINKED ISSUE #687: [ADAP-503] [Regression] Persisted Metadata does not update on BigQuery tables
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After upgrading to dbt 1.5.0 column metadata does not update in BigQuery and the model build shows as failed.

### Expected Behavior

metadata writes to the tables without issue in BigQuery.

### Steps To Reproduce

1. with dbt 1.5.0, writing to BigQuery
2. Update your dbt_project:
    +persist_docs:
      relation: true
      columns: true
3. Run a model with column level documentation
4. Error received after model is fully built, during the docs persist phase.

### Relevant log output

```shell
Error: google.api_core.exceptions.BadRequest: 400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/{table_path}?prettyPrint=false: Policy tags can only be attached to a leaf field.
```

### Environment

```markdown
- OS:debian
- Python:3.9.10
- dbt:1.5.0
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

I rolled back to 1.4.6 and the issue went away.

### PR DESCRIPTION
**Pull request by dgreen161**
resolves #687

### Description

This resolves the issue where policy tags attempting to be applied to structs (records) in BigQuery. These can only be applied to leaf nodes as described in the docs [here](https://cloud.google.com/bigquery/docs/column-level-security#struct_or_record)

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by dgreen161** [comment]
@cla-bot check

**Comment by nssalian** [comment]
Thanks for the fix, @dgreen161. Do you mind adding a test for this?

**Comment by dgreen161** [comment]
@nssalian I've updated the original test that introduced this functionality to also test for structs along with columns. Let me know if this needs to be updated

**Review by nssalian — APPROVED** [review]
looks good. FYI: @dbeatty10

**Comment by VersusFacit** [comment]
Doesn't this one need to be 1.5 backported to 1.5 @nssalian ?

**Pull request merged**
