### PR TITLE
[Bigquery] unit test tests + support for complex types

### LINKED ISSUE #1090: [Unit Testing] Support primative types + objects and arrays in dbt-snowflake
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently, the unit testing framework in core uses the `safe_cast` utils macro to convert a user-provided value for an input mock to the appropriate type. In some instances, this `safe_cast` may fail and need special handling depending on the type. 

The acceptance criteria for this issue is to introduce a test that provides coverage across any non-STRUCT input types for unit testing input data, potentially updating the `safe_cast` macro as necessary. 

### Describe alternatives you've considered

_No response_

### Who will this benefit?

_No response_

### Are you interested in contributing this feature?

yes

### Anything else?

STRUCT support is out of scope for this initial leg of work.

### PR DESCRIPTION
**Pull request by MichelleArk**
resolves #1090 
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) dbt-labs/docs.getdbt.com/#

### Solution
* Adds test implementations for base tests around unit testing
* expands coverage for safe_cast macro.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Comment by github-christophe-oudar** [comment]
Quick question, are the STRUCTs supported? If not, is planned as well? Thanks!

**Comment by MichelleArk** [comment]
@github-christophe-oudar - sorry for the delayed response but short answer is - yes!

**Comment by MichelleArk** [comment]
Failing test looks unrelated: https://github.com/dbt-labs/dbt-bigquery/actions/runs/7807239952/job/21295234626?pr=1031

Should be fixed by: https://github.com/dbt-labs/dbt-common/pull/69

**Comment by github-christophe-oudar** [comment]
@MichelleArk, great! I saw the commit yesterday 🚀 
I'm watching the PR and I'll test it once it's merged on the main branch 👍  (maybe before locally if I find some time to tinker)

**Review by mikealfare — APPROVED** [review]

**Comment by github-christophe-oudar** [comment]
Just wanted a quick follow up here to say that we're already using unit tests in production [beside for the models using UDFs](https://github.com/dbt-labs/dbt-bigquery/issues/1090#issuecomment-1986336098).
My coworker will soon release an article about our usage 👍

**Comment by martynydbt** [comment]
Looking forward to reading it! @github-christophe-oudar Thank you for sharing!

**Pull request merged**
