### PR TITLE
Requiring Python >=3.8 enables walrus operator

### LINKED ISSUE #849: [ADAP-757] SyntaxError: walrus operator in Python 3.7
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

SyntaxError in Python 3.7 with version >=1.5.4 due to [walrus operator](https://github.com/dbt-labs/dbt-bigquery/blob/2bce97721fb7f7733e0a49ec97430072720d7033/dbt/adapters/bigquery/column.py#L230).

### Expected Behavior

No SyntaxError or unable to install these versions with Python 3.7

### Steps To Reproduce

```bash
python3.7 -m venv /tmp/dbt-venv
source /tmp/dbt-venv/bin/activate
pip install dbt-bigquery
python -c "from dbt.adapters.bigquery.column import BigQueryColumn"
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/dbt-venv/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>
    from dbt.adapters.bigquery.column import BigQueryColumn  # noqa
  File "/tmp/dbt-venv/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230
    if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):
                                         ^
SyntaxError: invalid syntax
```

### Environment

```markdown
- OS: Lubuntu 22.04
- Python: 3.7
- dbt-core: 1.5.4
- dbt-bigquery: 1.5.4
```

### Additional Context

I believe this line line should be updated: https://github.com/dbt-labs/dbt-bigquery/blob/2bce97721fb7f7733e0a49ec97430072720d7033/setup.py#L94

### PR DESCRIPTION
**Pull request by dbeatty10**
resolves #849
[docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose) N/A

### Problem & Solution

The problem and solution are explained clearly in https://github.com/dbt-labs/dbt-bigquery/issues/849

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [ ] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc)

### CODE REVIEW

**Comment by dbeatty10** [comment]
Could we backport this as well?

**Review by mikealfare — APPROVED** [review]

**Comment by mikealfare** [comment]
> Could we backport this as well?

Agreed. We need to backport it all the way since py37 is EOL and no longer supported.

**Comment by mikealfare** [comment]
@dbeatty10, do you mind updating the comment at the top of `setup.py` as well? It doesn't do anything, but if we're updating this, we might as well do both.

**Comment by dbeatty10** [comment]
> @dbeatty10, do you mind updating the comment at the top of `setup.py` as well? It doesn't do anything, but if we're updating this, we might as well do both.

I updated the comment to be evergreen:
```diff
- # require python 3.7 or newer
+ # require a supported version of Python
```

**Pull request merged**
