### PR TITLE
Make `grant_access_to ` thread safe

### PR DESCRIPTION
**Pull request by judahrand**
resolves #

### Description

This PR aims to prevent the 412 PreConditionFailed error which is referenced here: https://github.com/dbt-labs/docs.getdbt.com/pull/634

Fixes: #266 

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [ ] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by judahrand** [comment]
@jtcohen6 Is this something which you think is worth merging / looking at?

**Comment by jtcohen6** [comment]
@judahrand Thanks for the bump! I'm going to mark this as ready for review by the Core-Adapters engineering team. They have a lot on their plate right now, so it might be a bit before one of them can take a look. I definitely think this would represent an improvement over the status quo, until we can revisit authorized views more holistically in the future.

**Comment by cwelton** [comment]
Is this moving forward?  Does the solution need work? 

Running into the #266 and wondering when it will get fixed.

**Comment by judahrand** [comment]
@colin-rogers-dbt is this merge-able?

**Comment by colin-rogers-dbt** [comment]
hey @judahrand apologies on the delay, I've been digging into this issue and might have an alternate solution to consider here as well. Have you tested this/seen if it has a performance impact?

**Pull request closed without merging**
