### PR TITLE
Feature/add quota project option

### LINKED ISSUE #1343: [Feature] Add the ability to specify a quota project in the bq connection profile
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I want the ability to specify a GCP `quota_project` on top of the existing `project` and `execution_project` in the dbt profile as an optional parameter. The reason for this being that this allows the user to specify which quota project to use when submitting a query, rather than defaulting to the quota project of where the account is defined. For example, when impersonating a service account this defaults to the project that the service account was created in.

This will mean users can set a quota project of their choosing independent of where they execute the query from

GCP docs overview of Quota Projects [here](https://cloud.google.com/docs/quotas/quota-project)

### Describe alternatives you've considered

As the quota project is not set by the dbt adapter now when it sets up the client the only way around this is to ensure whatever account you are using has been setup in the quota project you intend to use so it defaults to it. This is the reason I spotted this. I will raise a bug outlining that issue and link to it here #TODO

### Who will this benefit?

This will benefit anyone who wants to override the default quota project when running their dbt models. Also, it will fix a bug that currently blocks users impersonating service accounts which have been setup in projects that **do not have the BQ API enabled** as outlined in this bug issue #TODO

### Are you interested in contributing this feature?

Yes I am. I have made the changes on a feature branch but will require some guidance on the approach I have taken

### Anything else?

I have not contributed to something like this before and there will almost certainly be something I have missed or misunderstood. I have done my best to follow everything outlined in the contributing guide but please do not hold back if there's something that needs to be called out. I will not be offended as it will only help my understanding!

### LINKED ISSUE #1344: [Bug] Impersonating Service Account - Defaults GCP `quota_project` to project where SA is defined
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using the `impersonate_service_account` setting in the `profiles.yml` for BigQuery it will default the `quota_project` for the `client_options` to `None`. It will then use the project that the service account is defined in as the quota project.

This means that if the service account a user sets is defined in a project that does not have the BigQuery API enabled in it will fail, no matter what `execution_project` or `project` are set to in the `profiles.yml` as these are separate to the quota project.

### Expected Behavior

A user should be able to override and set the quota project in the configuration of the dbt profile rather than it defaulting to the project the service account is defined in. A user should not have to enable the BigQuery API for a project that a service account lives in if BigQuery is not required in that project.

### Steps To Reproduce

1. Setup a python venv and pip install the following versions
- `pip install dbt-core==1.8.6 dbt-bigquery==1.8.2`

2. Setup three separate GCP projects (the names of which will have to be unique to yourself)

  **MY_SERVICE_ACCOUNT_PROJECT**: 
  - Create a service account called `dbt-sa`
  - Give your user service account token creator role on the above SA so that you can impersonate it
  
  **MY_DATA_PROJECT**:
  - Enable BQ API and create a dataset called `foo` within it
  - Give service account above `roles/bigquery.dataViewer` to the dataset
  
  **MY_EXECUTION_PROJECT**: 
  - Enable BQ API
  - Give service account above `roles/bigquery.jobUser` to the project

3. Create a `profiles.yml` configuration that contains the following and substitute the names of your GCP projects with those you have created.

```yaml

  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      schema: foo
      location: europe-west2
      priority: interactive
      project: $MY_DATA_PROJECT
      execution_project: $MY_EXECUTION_PROJECT
      impersonate_service_account: "dbt-sa@${MY_SERVICE_ACCOUNT_PROJECT}.iam.gserviceaccount.com"
```

4. Run the following dbt command and point to wherever you have stored your `profiles.yml` file defined above

```bash
dbt debug --connection --profiles-dir .

```

This will error on the connection and complain that the BQ API is not enabled in the project, it will link you to the project that the service account is defined in and crucially not the `project` or `execution_project` set in the profile.

### Relevant log output

```shell
❯ dbt debug --connection --profiles-dir .
22:22:11  Running with dbt=1.8.6
22:22:12  dbt version: 1.8.6
22:22:12  python version: 3.12.1
22:22:12  python path: /Users/jackcarpenter/.pyenv/versions/3.12.1/envs/dbt-bigquery-bug/bin/python
22:22:12  os info: macOS-13.2.1-x86_64-i386-64bit
22:22:13  Using profiles dir at .
22:22:13  Using profiles.yml file at ./profiles.yml
22:22:13  Using dbt_project.yml file at /Users/jackcarpenter/dbt-bigquery-bug/dbt_project.yml
22:22:13  adapter type: bigquery
22:22:13  adapter version: 1.8.2
22:22:13  Skipping steps before connection verification
22:22:13  Connection:
22:22:13    method: oauth
22:22:13    database: MY_DATA_PROJECT
22:22:13    execution_project: MY_EXECUTION_PROJECT
22:22:13    schema: foo
22:22:13    location: europe-west2
22:22:13    priority: interactive
22:22:13    maximum_bytes_billed: None
22:22:13    impersonate_service_account: dbt-sa@MY_SERVICE_ACCOUNT_PROJECT.iam.gserviceaccount.com
22:22:13    job_retry_deadline_seconds: None
22:22:13    job_retries: 1
22:22:13    job_creation_timeout_seconds: None
22:22:13    job_execution_timeout_seconds: 5000
22:22:13    timeout_seconds: 5000
22:22:13    client_id: None
22:22:13    token_uri: None
22:22:13    dataproc_region: None
22:22:13    dataproc_cluster_name: None
22:22:13    gcs_bucket: None
22:22:13    dataproc_batch: None
22:22:13  Registered adapter: bigquery=1.8.2
22:22:15  BigQuery adapter: https://console.cloud.google.com/bigquery?project=MY_EXECUTION_PROJECT&j=bq:europe-west2:7388df4b-c857-4aef-8af5-5f97d9a5ff74&page=queryresults
22:22:15    Connection test: [ERROR]

22:22:15  2 checks failed:
22:22:15  Project loading failed for the following reason:
 project path </Users/jackcarpenter/dbt-bigquery-bug/dbt_project.yml> not found

22:22:15  dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  BigQuery API has not been used in project xxxxxxxxxxxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/bigquery.googleapis.com/overview?project=xxxxxxxxxxxxx then retry
. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile

```
```


### Environment

```markdown
- OS: macOS Ventura 13.2.1
- Python: 3.12.1
- dbt-core: 1.8.6
- dbt-bigquery: 1.8.2
```

### Additional Context

This relates to a feature request I have also raised #1343 that outlines a solution/improvement that I think may work

### LINKED ISSUE #1347: [Bug] BQ quota_project defaults to the account/user's environment default
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When a user or service account's default `quota_project_id` is set to a project other than the `execution_project` specified in the `profiles.yml` DBT will use this as the `quota_project_id` in the underlying request opposed to anything set in the `profiles.yml`. This is a side effect and will mean that a **DBT will fail to connect to BigQuery if the user does not have BigQuery API enabled in the project their credentials default to**. It will also mean that certain quota limits are being used up in the default project.

You can see the default quota project_id from the contents of your `application_default_credentials` file. It should look something like this. A similar structure applies to the contents of service account keys I believe

```json

{
  "account": "",
  "client_id": "xyz.apps.googleusercontent.com",
  "client_secret": "xyz",
  "quota_project_id": $MY_QUOTA_PROJECT,
  "refresh_token": "xyz",
  "type": "authorized_user",
  "universe_domain": "googleapis.com"
}

```

This issue arose when running a CI/CD pipeline that is defined in a project separate to either the `project` or `execution_project` and did not have the BQ API enabled, so it failed to connect.

### Expected Behavior

**What I think should be happening according to the docs**

As this is a side effect the expected behaviour is a bit difficult to define but DBT should either set `execution_project` as the `quota_project_id` in the BQ client or allow the user to override it themselves in the `profiles.yml`.

In my opinion the user should be able to specify a separate optional `quota_project` to use separate from `project` and `execution project`. By not setting it, it will default to what it does now and not change the behaviour. Feature Request here #1343 

### Steps To Reproduce

1. Create a GCP quota Project and **do not enable the BQ API** in it. This is to ensure there is no quota to use for it
2. Create a GCP data project, enable BQ API and create a dataset called `foo`
3. Create a GCP execution project, enable BQ API
4. Make sure you user has access to all three of the above with the appropriate BQ permissions
5. Running your local gcloud run the following `gcloud config set project $MY_QUOTA_PROJECT` (replace with the name of step 1)
6. Generate your local oauth credentials `gcloud auth application-default login`
7. You should then be able to cat the contents of that file using `cat ~/.config/gcloud/application_default_credentials`. It should look something like the following 
```json
{
  "account": "",
  "client_id": "xyz.apps.googleusercontent.com",
  "client_secret": "xyz",
  "quota_project_id": $MY_QUOTA_PROJECT,
  "refresh_token": "xyz",
  "type": "authorized_user",
  "universe_domain": "googleapis.com"
}
```
8. Setup a python virtualenv and `pip install dbt-core==1.8.6 dbt-bigquery==1.8.2`
9. Create a profiles.yml configuration that contains the following and substitute the names of your GCP projects with those you have created
```yaml
default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      schema: foo
      location: europe-west2
      threads: 10
      timeout_seconds: 5000
      priority: interactive
      retries: 1
      project: $MY_DATA_PROJECT
      execution_project: $MY_EXECUTION_PROJECT
```
10. Run the following dbt command to run the debug of the connection (update `profiles-dir` to wherever your profile is located
`dbt debug --connection --profiles-dir .`

You should then see a log output like the below. Here you can see the quota project is causing this connection to fail even though it is not specified anywhere in the dbt profile itself and is instead being picked up from the environment.

### Relevant log output

```shell
13:24:42  dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  BigQuery API has not been used in project $MY_QUOTA_PROJECT before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/bigquery.googleapis.com/overview?project=$MY_QUOTA_PROJECT then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

### Environment

```markdown
- OS: macOS Ventura 13.2.1
- Python: 3.12.1
- dbt-core: 1.8.6
- dbt-bigquery: 1.8.2
```

### Additional Context

This relates to #1343 a feature request to add quota_project and a potential PR for it here  #1345

Docs PR : dbt-labs/docs.getdbt.com#6054

As noted on the #1343 I have not raised a change to a dbt adapter before so please do let me know if I am misunderstanding anything

### PR DESCRIPTION
**Pull request by jcarpenter12**
resolves #1343 
resolves #1344 
resolves #1347

Docs PR dbt-labs/docs.getdbt.com#6054

### Problem

Currently it is not possible to set a quota project in the `profiles.yml` configuration for BigQuery. This means that the quota project defaults to the quota project of the credentials. This can cause issues if using an account to auth that does not have the BQ API enabled (see bug here #1347 ). It also means that users can not run their models under a specific quota project if they want to.

### Solution

Add an optional `quota_project` param in the profiles.yml that will allow a user to set a quota project if they want to. If they do not set it the behaviour will not change. The only override being applied is a `config_option` for the quota project that defaults to None anyway.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX

### CODE REVIEW

**Review by github-christophe-oudar — APPROVED** [review]

**Comment by jcarpenter12** [comment]
@colin-rogers-dbt thank you for taking a look at this, do you know what the next steps with might look like? Am i right in thinking that if this change is merged it will be in the next release? Do you happen to know when that release is likely to be?
The reason I ask is that this change would resolve a bug in our CI pipelines (service accounts are defined in a project that does not have BQ API enabled, so they fail), so currently I am holding off making a workaround if this feature is in the next release

**Comment by jcarpenter12** [comment]
> > @jcarpenter12 Sorry for the radio silence here, this is a great PR! Ideally we would like to add a functional test (likely similar to how [we test](https://github.com/dbt-labs/dbt-bigquery/blob/main/tests/functional/test_location_change.py#L28) location config to make sure we don't break this in the future. If that's something you're comfortable doing, go for it, otherwise someone on our team can take this over and add it.
> 
> apologies for not getting back to you sooner @colin-rogers-dbt , didn't get a notification for some reason. I will take a look and check my understanding and get back to you. Thanks for your help!

@colin-rogers-dbt i've had a crack at adding a functional test. I've tested it locally and it works with the temp GCP projects I setup to mirror what your CI jobs are doing. It has two use cases, one for if no quota project is set which is the default and another for whether an alternate quota project is set. I have tested locally and it passes for those two use cases but understand if this is not quite what you're after, happy to update it if so

**Review by mikealfare — APPROVED** [review]
Thanks for a thorough PR @jcarpenter12! I appreciate testing both the case with and without the new config, the latter is often missed. And thank you for the docs PR as well!

**Comment by jcarpenter12** [comment]
> Thanks for a thorough PR @jcarpenter12! I appreciate testing both the case with and without the new config, the latter is often missed. And thank you for the docs PR as well!


thanks @mikealfare I can see that the test is failing on the CI as the service account doesn't have the service usage consumer role on the `BIGQUERY_TEST_ALT_DATABASE` which I have used as the optional quota project. This wasn't an issue when running locally obviously as I had access to the project I setup. I am not sure how you would like to proceed on this one. Two options I would guess being give the SA that role on that existing project or setup a new project specifically just for this quota test and give it that role on the new project, but up to whoever owns these GCP projects.

**Pull request merged**
