### PR TITLE
Add support for custom containers while using dataproc serverless

### LINKED ISSUE #642: Add support for custom containers while using dataproc serverless
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I would like to use a custom container for my dataproc serveless jobs.

### Describe alternatives you've considered

Dataproc serverless does not offer the ability to install extra packages in their standard runtime. The only other way I could add unsupported dependencies is by using a cluster.

### Who will this benefit?

Users creating python models with additional dependencies not supported by the standard dataproc serverless runtime.

### Are you interested in contributing this feature?

I have a working fork but haven't run the test suite yet.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by bveber**
resolves #642 

### Description

The current implementation only supports the standard spark runtime provided by dataproc serverless which does not allow installation of additional dependencies. The custom container can be defined in the runtime_config that is passed to the dataproc call. It expects an image that exists in Container Registry or Artifact Registry with a naming format like {hostname}/{project-id}/{image}:{tag}.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-bigquery/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

**Comment by joellubi-cherre** [comment]
This would very valuable for us in making dbt python models feasible in our stack. Are there any unmet requirements for change this to be reviewed? Anything I could contribute to help unblock this?

**Comment by bveber** [comment]
@Fleid @nathaniel-may Just bumping this since there seems to be interest in this enhancement beyond myself

**Review by alyce-cherre — COMMENTED** [review]
Very eager for this to come out!!!

It'll help us make the case to productionize more of our ML models using dbt/python instead of using native GCP/AWS products

**Comment by thumarrushik** [comment]
+1

**Comment by fdiaspp** [comment]
+1

**Comment by DouglasNorrgard** [comment]
+1

Very eager. Implementation could be very similar to the new dataproc_batch-config?

**Comment by c0nn0rstevens** [comment]
Is there any progress on this? This is something my team would really benefit from. What is still needed for this? Can I help somehow?

**Comment by ShahbalKhan** [comment]
This feature is quite useful for avoiding managing custom clusters for our pyspark transformations. Would love to have it pushed. Also happy to contribute where required.

**Pull request closed without merging**
