### PR TITLE
enrich adapter response for UPDATE and SELECT queries

### LINKED ISSUE #68: `UPDATE` operation is missing a useful AdapterResponse
### Describe the bug
When calling load_result() from a statement block connecting to a bigquery db, if the query is an UPDATE operation, we do not get an AdapterResponse on par with other DML operations.

Seems like it should be included here: https://github.com/dbt-labs/dbt-bigquery/blob/95ca84b5100c2b940751d8a65aaeb914df211ac7/dbt/adapters/bigquery/connections.py#L417

Moreover, what is the reason that `SELECT` statements do not also get a filled out AdapterResponse?

### Steps To Reproduce
```
{% macro test_response_object() %}
{% call statement('test') %}
... UPDATE STATEMENT ...
{% endcall %}
{% set result = load_result('test') %}
{{ dbt_utils.log_info(result) }}
{% endmacro %}
```
From the command line:
`dbt run-operation test_response_object`

Result:
```
{'response': BigQueryAdapterResponse(_message='OK', code=None, rows_affected=None, bytes_processed=None), 'data': [], 'table': <agate.table.Table object at 0x114f1cd90>}
```

### Expected behavior
BigQueryAdapterResponse field should be populated with values reported by the BigQuery API. Here is an example of what you get when you run a DELETE:
```
{'response': BigQueryAdapterResponse(_message='DELETE (1.0 rows, 352.5 KB processed)', code='DELETE', rows_affected=1, bytes_processed=360929), 'data': [], 'table': <agate.table.Table object at 0x1065e82b0>}
```

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 0.21.0

Up to date!

Plugins:
  - bigquery: 0.21.0
  - snowflake: 0.21.0
  - redshift: 0.21.0
  - postgres: 0.21.0
```

**The operating system you're using:**
macOS v 11.6 (20G165)

**The output of `python --version`:**
`Python 3.8.11`

### PR DESCRIPTION
**Pull request by rjh336**
resolves #68 

### Description

Add logic in `BigQueryConnectionManager.execute` to enrich the response with more info for UPDATE and SELECT statements. 

UPDATE responses will match that of other DML operations, while SELECT will return the following:
- `bytes_processed` = total reported bytes processed from running the SELECT statement
- `rows_affected` = number of rows in the query result

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] I have updated the `CHANGELOG.md` and added information about my change to the "dbt-bigquery next" section.

### CODE REVIEW

**Comment by McKnight-42** [comment]
HI, reviewed and passed it onto testing till @jtcohen6 has a chance to take a look, but noticed that your code is a little out of date and would love if it if you could update your branch with latest from main and make sure tests still pass.

**Comment by McKnight-42** [comment]
Hi just wanting to pass along that you may need to merge main again, had a minor update to the bigquery tests should clear up the python tests that are failing currently, will try to help with the flake8 test if its still failing as well.

**Comment by rjh336** [comment]
Thanks @McKnight-42 - all up to date now :)

**Review by McKnight-42 — APPROVED** [review]
worked locally for me, thank you for taking time to work on this enhancement.

**Pull request merged**
